#!/bin/sh

set -eu
set -x

# This should be aligned with host setup instructions in README.md...
sed -i -e 's/^# deb-src/deb-src/' /etc/apt/sources.list

apt-get update
apt-get upgrade -y

# Turn off synches on every dpkg write to speed things up
echo force-unsafe-io > /etc/dpkg/dpkg.cfg.d/02apt-speedup

# Turn off man updates to speed up package installation
echo 'man-db man-db/auto-update boolean false' | debconf-set-selections

# Avoid gpg (used by adt-run) stalling machine due to lack of entropy
apt-get install -y --force-yes rng-tools
rngd -b -r /dev/urandom

# Some packages need wget to download tests
apt-get install -y wget

# Install packages for debugging errors inside chroot
apt-get install -y vim gdb valgrind strace
