#!/bin/sh -eu

# Copyright 2017 Yury Gribov
#
# Use of this source code is governed by MIT license that can be
# found in the LICENSE.txt file.

REAL=/usr/bin/$(basename $0)

# Remove ourselves from PATH (to avoid recursion)
PATH=$(echo "$PATH" | tr : '\n' | grep -v gcc-wrappers | tr '\n' :)

# TODO: add -lpthread, -dl ? Failed packages are gpg, procps, rsyslog, db5.3 (java)
exec $REAL "$@" -fsanitize=address -fsanitize-recover=address -fno-omit-frame-pointer -U_FORTIFY_SOURCE
