#!/bin/sh -eu

# Copyright 2017 Yury Gribov
# 
# Use of this source code is governed by MIT license that can be
# found in the LICENSE.txt file.

if test $# != 1; then
  cat <<EOF
Usage: $(basename $0) LOG_PATH
Finds "interesting" messages in pbuilder logs.
EOF
  exit 1
fi

# TODO: make signals case-sensitive?
GOOD_RE='Segmentation fault\|Bus error\|Illegal instruction\|Abort\|Terminated\|Killed\|\<SEGV\>\|\<TRAP\|ABORT\|assertion\|error:\|failed\|segfault'
BAD_RE='failed to verify signature\|Terminated.*sleep'

cd $1
grep -ri "$GOOD_RE" . | grep -v "$BAD_RE"
