#!/bin/sh -eu

# Copyright 2017 Yury Gribov
# 
# Use of this source code is governed by MIT license that can be
# found in the LICENSE.txt file.

# Usage: find_bugs DIR
# Finds "interesting" messages in pbuilder logs.

# TODO: make signals case-sensitive?
GOOD_RE='Segmentation fault\|Bus error\|Illegal instruction\|Abort\|Terminated\|Killed\|\<SEGV\>\|\<TRAP\|ABORT\|assertion\|error:\|failed\|segfault'
BAD_RE='failed to verify signature'

cd $1
grep -ri "$GOOD_RE" . | grep -v "$BAD_RE"
