#!/bin/sh -eux

# Ensure output file is writable by all users
touch $SHARED_DIR/output/sortcheck.log
chmod a+rwx $SHARED_DIR/output/sortcheck.log

# Quick verification
LIB=$SHARED_DIR/sortcheck/bin/libsortcheck.so
test -x $LIB
! LD_PRELOAD=$LIB ls 2>&1 | grep -q ERROR

# LD_PRELOAD will not work for setuids
echo $LIB >> /etc/ld.so.preload
