#!/bin/sh -ex

# Copyright 2015-2017 Yury Gribov
# 
# Use of this source code is governed by MIT license that can be
# found in the LICENSE.txt file.

# Allow analyzer to copy additional outputs
if test -n "${ENABLE_HOOKS:-}" -a -x $SHARED_DIR/hooks/finish; then
  $SHARED_DIR/hooks/finish
fi

# Ensure that test_pkgs can access files
chmod -R a+rw $SHARED_DIR/output

if test -n "$SHELL_ON_ERROR"; then
  echo "Running shell on error"
  cd /tmp/buildd/*/debian/..
  $(dirname $0)/run-shell
fi
