#!/bin/sh -ex

# Copyright 2015-2017 Yury Gribov
# 
# Use of this source code is governed by MIT license that can be
# found in the LICENSE.txt file.

apt-get install -y --force-yes vim less bash gdb
/bin/bash < /dev/tty > /dev/tty 2> /dev/tty
