#!/bin/sh -eux

apt-get -y install llvm llvm-dev libclang-dev clang

# Ensure output file is writable by all users
touch $SHARED_DIR/output/sortcheck.log
chmod a+rwx $SHARED_DIR/output/sortcheck.log

# Quick verification
apt-get -y install file
file -L `which cc` | grep 'POSIX shell script'
