#!/bin/sh

set -e
set -x

test -d "$SHARED_DIR"
test -n "$SORTCHECK_OPTIONS"

touch $SHARED_DIR/sortcheck.log
chmod 777 $SHARED_DIR/sortcheck.log

# Build and install checker
make -C $SHARED_DIR/sortcheck clean all DEBUG=1
cp $SHARED_DIR/sortcheck/bin/libsortcheck.so /usr/lib
echo /usr/lib/libsortcheck.so >> /etc/ld.so.preload

# Avoid gpg (used by adt-run) stalling machine due to lack of entropy
apt-get install -y --force-yes rng-tools
rngd -b -r /dev/urandom

# Turn off man updates to speed up package installation
echo 'man-db man-db/auto-update boolean false' | debconf-set-selections
