#!/bin/sh -eux

chmod a+w $SHARED_DIR/output

LIB=$SHARED_DIR/valgrind-preload/bin/libpregrind.so

# Disable ASLR to get reproducible stacktraces
echo 0 > /proc/sys/kernel/randomize_va_space

test -x $LIB
! LD_PRELOAD=$LIB ls 2>&1 | grep -q ERROR
! LD_PRELOAD=$LIB PREGRIND_VERBOSE=1 g++ -c -x c /dev/null 2>&1 | grep -q 'cc1: blacklisted'

echo $LIB >> /etc/ld.so.preload

echo "Installed Pregrind"
